#ifndef IMAGE_BLUR_PLUGIN_GLOBAL_H
#define IMAGE_BLUR_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGEBLURPLUGIN_LIBRARY)
#define IMAGE_BLUR_PLUGIN_EXPORT Q_DECL_EXPORT
#else
#define IMAGE_BLUR_PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGE_BLUR_PLUGIN_GLOBAL_H
